server:
  servlet:
    context-path: /spring-cloud-hello/discovery
  port: 9000

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #\u4E0D\u8981\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    #\u7981\u6B62\u68C0\u7D22\u670D\u52A1
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
